### ISSUE TITLE
componentDidMount function & contained script purpose

### ISSUE THREAD

**Issue by aymendhaya** [aymendhaya/react-smartify#2]
Here in **SearchFormComponent**, script inside **componentDidMount** has no clear utility. What is the exact purpose of saving params into the current component _state_ since they are used by the child components directly from the url through _match.params_
 Also can you explain what is the purpose of using "ComponentDidMount" ?

> ```
>     componentDidMount(){
> 
>       if((this.props.match && this.props.match.params.search_type && this.props.match.params.search_text)){
> 
>         this.setState({search_type: this.props.match.params.search_type})
>         this.setState({search_text: this.props.match.params.search_text})
> 
>         if(this.props.match.params.art_id){
>           this.setState({art_id: this.props.match.params.art_id})
>         }
>         if(this.props.match.params.alb_id){
>           this.setState({alb_id: this.props.match.params.alb_id})
>         }
>         if(this.props.match.params.tra_id){
>           this.setState({tra_id: this.props.match.params.tra_id})
>         }
> 
>         this.search(this.props.match.params.search_type, this.props.match.params.search_text, true)
>       }
>     }
> ```

**Comment by ZiedHf** [comment]
First at all this code is unnecessary : 
`        if(this.props.match.params.art_id){
          this.setState({art_id: this.props.match.params.art_id})
        }
        if(this.props.match.params.alb_id){
          this.setState({alb_id: this.props.match.params.alb_id})
        }
        if(this.props.match.params.tra_id){
          this.setState({tra_id: this.props.match.params.tra_id})
        }`

I went in different logic from the beginning and changed the code many different time. Tried to delete what's useless everytime I find it out but it seems like I missed some lines.

Now, we got this function : 
`componentDidMount(){

      if((this.props.match && this.props.match.params.search_type && this.props.match.params.search_text)){
        this.setState({search_type: this.props.match.params.search_type})
        this.setState({search_text: this.props.match.params.search_text})
        this.search(this.props.match.params.search_type, this.props.match.params.search_text, true)
      }
    }`

Here I just want to keep the data only in the state as a **source of truth**.
In **SearchFormComponent** there are two ways to initialize the data : 

- From the router.
- In the form, by typing.

The router is updated according to the typing at the first time I was working on the router in **SearchFormComponent** but it seemed a little bit weird so I changed the source of truth to the state at the router changed only by clicking on the button search.

When the user search using router, **componentDidMount** will handle the job, So when the page renders the component, the state changes according to the route, the form will be updated as well.

I can't use **componentWillMount** since I use the function **setState** here, in the ReactJs documentation they warn to never use it both since it may cause some defects. Otherwise, I think I can use **componentwillreceiveprops** since this function is triggred everytime the props changes, but I didn't try it instead of **componentDidMount**.

**Comment by aymendhaya** [comment]
If you simply do `onChange={e => setState( ... )}` on both **input** and **select**, the **search_text** and **search_type** on the state will get updated automatically on every values change. so when you click the button search, the function associated to the button should only contain `this.props.history.push(/this.state.search_text+"/"+this.state.search_type)`. **SearchFormComponent** is routeless and doesnt need any data from the URL he only make the first update of the url. concerning the functions related to react:
1- **componentWillMount** is the same as the constructor, so 99% of the cases if you need to execute something before the component is mounted, constructor do the job.
2- **componentDidMount** is the same as document.ready on non-modern web development

Notes that the 5 or 6 functions related to react are just a first aid kit for some rare use cases, and it will be better to avoid using them only in case of need (we will see some cases later)

In **searchFormComponent** there is no data to be initialised, this component doesnt depend on any param and dont need to store any data from the URL. so you can remove all uses of routes data and your search function will only contain a simple line of `history.push` having **search_text** and **search_type** from the state who get updated automatically and every input or select values change through the` onChange={this.setState( ... )}`

**Comment by ZiedHf** [comment]
@aymendhaya  Check it out. I tried to enhance the code according to your suggestions. 
I'm trying to verify all the issue after this change, hope it works well.

**Comment by aymendhaya** [comment]
Perfect for most on it.

Now concerning this part:

> search_text: (this.props.match.params.search_text) ? this.props.match.params.search_text : '',
> search_type: (this.props.match.params.search_type) ? this.props.match.params.search_type : '',
>  search: ((this.props.match.params.search_text) && (this.props.match.params.search_type)) ? true : false 

first of all, in itenary conditions, if you have a value on the condition that you want to return it if its true 

> ( x ? x : y )

 _(like on search_text and search_type)_ you can just write

>  x || y

for the case of boolean values

>  x ? x : !x

(like in state.search) you can just right the value itself: 

> (x ? x : !x) is the same as (x) itself.

 
So you will have:
> search_text: this.props.match.params.search_text || '',
> search_type: this.props.match.params.search_type || '',
>  search: (this.props.match.params.search_text && this.props.match.params.search_type) 

Final things, 
- i can't find any use of the boolean `this.state.search` in your code except setting it to true on search function. You can remove it if you don't need it
- As we talk about it before, try to avoid using `bind(this)` its not a good practice for advanced react users

**Comment by ZiedHf** [comment]
@aymendhaya Great, the code is legible now.

For `this.state.search` I turn it to false after any `onChange` affects the `search_text` or the `search_type`, I want to keep the current result until the user click the search button.
`this.state.search` is true by clicking the search button or when the user searches using router.
