### ISSUE TITLE
Calling searchResultComponent using Route

### ISSUE THREAD

**Issue by aymendhaya** [aymendhaya/react-smartify#4]
>        <Switch>
>                       {(this.state.search_type === "track") ? <Route path='/search/:search_type/:search_text/:tra_id?' component={SearchResultComponent}/> : null}
>                       {(this.state.search_type === "album") ? <Route path='/search/:search_type/:search_text/:alb_id?/:tra_id?' component={SearchResultComponent}/> : null}
>                       {(this.state.search_type === "artist") ? <Route path='/search/:search_type/:search_text/:art_id?/:alb_id?/:tra_id?' component={SearchResultComponent}/> : null}
>                       {/* <Route path='/search/:search_type/:search_text/:art_id?/:alb_id?/:tra_id?' component={SearchResultComponent}/> */}
>                     </Switch>

Here you are calling **searchResultComponent** 3 times. You need to render _one Route (calling searchResultComponent)_ without any condition (it will be rendered but empty) or render it if `match.param.search_text` and `match.param.search_type` exists. but inside of **searchResultComponent** you will make a conditional render according to search_type so you will bring **ArtistComponent** if _search_type = 'artist'_, **AlbumComponent** _if search_type='album'_ or **TrackComponent** if _search_type='track'_

**Comment by ZiedHf** [comment]
@aymendhaya Please take a look, I haven't finished yet all the points but I want you to check if this is the right structure of project.

**Comment by aymendhaya** [comment]
@ZiedHf  will need simply to make one function that execute `search()` or get` albumbyartist()` according to the **search_type** value

> this.props.match.params.search_type === 'artist' ? e => getAlbumbyArtist(match.param.artID) : e => search(searchText, searchType)

Almost the same case for `handleRouter()`, we dont neeed to check **search_type** as a string since we can get it as a `match.param`. you will build the link that will be pushed according to **search_type**

> handleRouter(){
> let path = this.props.match.param.search_type === 'artist' ? .... : .....
> this.props.history.push(path)
> }

**Comment by ZiedHf** [comment]
@aymendhaya I want to get rid of the `(this.state.search)` in `SearchFormComponent` so I write the Route without any condition :
```jsx
{ (this.state.search) &&
                      <Route path='/search/:search_type/:search_text/:art_id?/:alb_id?/:tra_id?' component={SearchResultComponent}/>
                  }
```
The problem here that if the user searches twice using the same type the output will never change ! Despite that the route was updated and the data was sent successfully throughout the `ResultFormComponent` until `ArtistComponent`. But this last one never refreshes the output because the DoSearch was called in the constructor and the component was already displayed !

I can't call `doSearch` from the constructor neither in render because it contains the `setState` function. 

I find a solution but it depends on React Methods : **componentWillReceiveProps**
```jsx
componentWillReceiveProps(nextProps){
        if(this.props.match.params.search_text !== nextProps.match.params.search_text){
            //Different search text => Execute doSearch()
            this.doSearch(nextProps.match.params.search_text)
        }
    }
```
Should I proceed in this logic or I have missed something ?

**Comment by aymendhaya** [comment]
Yes, this is one of the rare cases where you should use `componentWillReceiveProps`
